apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pfm
  template: 
    metadata: 
      name: pfm-pod
      labels: 
        app: pfm
    spec:
      containers: 
        - name: pfm-container
          image: schmoe735/processed-future-movement:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pfm-service
spec:
  type: NodePort
  selector: 
    app: pfm
  ports: 
    - name: http
      port: 8080
      targetPort: 8080