inputfile: Input.txt

transactions-file:
  indexes:
    clientType:
      start: 4
      end: 7
    clientNumber:
      start: 8
      end: 11
    accountNumber:
      start: 12
      end: 15
    subAccountNumber:
      start: 16
      end: 19
    exchangeCode:
      start: 28
      end: 31
    productGroupCode:
      start: 26
      end: 27
    symbol:
      start: 32
      end: 37
    expirationDate:
      start: 38
      end: 45
    quantityLong:
      start: 53
      end: 62
    quantityShort:
      start: 64
      end: 73

